siege: implementing siege attack generator

diff --git a/examples/Makefile b/examples/Makefile
--- a/examples/Makefile
+++ b/examples/Makefile
@@ -8,5 +8,10 @@ express-async-error:
 	node ../bin/attack -r ./attack-routes.json -o async-results.txt -t ab -u http://localhost:5002 > express-async-error-attack.sh &&\
 	echo "Now run 'node express-async-error' and 'sh express-async-error-attack.sh' script in another terminal."
 
+siege:
+	ROUTES_ONLY=1 node ./express-sync-error.js &&\
+	node ../bin/attack -r ./attack-routes.json -o sync-results.txt -t siege -u http://localhost:5001 > siege-attack.sh &&\
+	echo "Now run 'node express-sync-error' and 'sh siege-attack.sh' script in another terminal."
+
 clean:
-	rm -rf *.sh attack-routes.json result.txt || true
+	rm -rf *.sh attack-routes.json result.txt *siege* || true
